*********************************************
2019-06-27:16:27:31   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:27:43   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:27:44   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:27:46   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:27:56   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:03   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:05   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:08   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:10   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:15   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:17   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:18   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:21   HTTPSConnectionPool(host='marketingplatform.google.com', port=443): Max retries exceeded with url: /about/enterprise/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000015C5BF3FB38>, 'Connection to marketingplatform.google.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:28:22   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:23   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:26   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:28   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:29   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:31   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:32   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:34   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:34   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:36   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:37   HTTPSConnectionPool(host='marketingplatform.google.com', port=443): Max retries exceeded with url: /about/enterprise/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000015C5BF3E7B8>, 'Connection to marketingplatform.google.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:28:39   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:41   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:44   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:46   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:47   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:51   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:51   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:54   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:28:56   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:57   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:28:59   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:00   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:00   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:01   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:05   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:06   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:06   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:10   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:12   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:13   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:16   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:17   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:19   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:20   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:23   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:24   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:26   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:30   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:30   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:33   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:35   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:36   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
***********************************
2019-06-27:16:29:39   HTTPConnectionPool(host='seo.chinaz.com', port=80): Read timed out. (read timeout=20)
*********************************************
2019-06-27:16:29:41   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
***********************************
2019-06-27:16:29:42   local variable 'r' referenced before assignment
*********************************************
2019-06-27:16:29:42   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:43   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:45   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:46   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:47   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:48   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:48   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:50   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:53   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:54   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:55   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:58   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:29:59   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:29:59   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:02   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:03   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:30:04   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:06   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:30:07   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:08   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:09   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:09   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:30:14   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:30:16   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:17   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:30:22   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:30:26   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:26   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:30:27   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:30   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:38   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:39   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:47   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:53   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:55   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:30:57   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:06   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:15   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:18   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:20   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:28   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:32   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:34   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:43   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:46   Exceeded 30 redirects.
*********************************************
2019-06-27:16:31:49   Exceeded 30 redirects.
*********************************************
2019-06-27:16:31:53   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:56   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:31:59   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:03   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:05   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:10   HTTPSConnectionPool(host='www.woyoo.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:32:19   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:23   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:24   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:28   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:37   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:38   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:44   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:46   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:32:56   HTTPSConnectionPool(host='www.jb51.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:33:05   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:09   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:14   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:23   HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EE1558ABA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
*********************************************
2019-06-27:16:33:25   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:27   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:27   HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EE1558AA58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
*********************************************
2019-06-27:16:33:44   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:48   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:49   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:33:56   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:08   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:09   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:30   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:33   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:38   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:45   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:54   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:34:59   HTTPSConnectionPool(host='www.jb51.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:34:59   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:05   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:35:06   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:35:12   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:13   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:23   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:32   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:33   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:40   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:41   HTTPSConnectionPool(host='www.easyzw.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:35:42   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:35:50   HTTPSConnectionPool(host='www.jb51.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:35:59   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:36:00   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:36:07   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:36:11   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:36:12   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:36:21   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:36:22   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:36:52   HTTPSConnectionPool(host='www.jb51.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:36:57   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:36:58   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:09   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:37:12   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:14   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:18   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:19   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:23   HTTPSConnectionPool(host='www.jb51.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:37:30   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:37:40   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:43   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:44   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:45   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:37:58   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:02   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:02   HTTPConnectionPool(host='tencentmessage', port=80): Max retries exceeded with url: /?uin=461478385&Site=www.jb51.net (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7262C9940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:38:09   HTTPConnectionPool(host='tencent', port=80): Max retries exceeded with url: //message/?uin=461478385&Site=//www.jb51.net (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7262C97B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:38:13   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:18   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:22   HTTPSConnectionPool(host='www.easyzw.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:38:23   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:25   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:28   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:32   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:38:35   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:38:36   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:37   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:38:48   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:55   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:38:56   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:39:05   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:12   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:16   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:20   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:27   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:35   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:40   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:42   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:44   HTTPSConnectionPool(host='www.easyzw.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:39:53   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:39:59   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:40:13   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:40:13   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:40:17   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:40:20   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:40:22   HTTPSConnectionPool(host='www.gezila.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:40:25   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:40:29   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:40:36   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:40:41   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:40:45   HTTPSConnectionPool(host='www.easyzw.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:40:49   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:40:49   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:40:51   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:41:06   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:41:07   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:41:17   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:41:21   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:41:24   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:41:31   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:41:42   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:41:47   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:41:52   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:02   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:08   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:14   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:42:22   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:24   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:26   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:31   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:42   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:46   HTTPSConnectionPool(host='m.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:42:47   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:42:50   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:43:01   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:43:03   HTTPSConnectionPool(host='www.freebuf.com,', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001EE139F5828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:43:03   HTTPSConnectionPool(host='account.top', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B4ED030F60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:43:05   HTTPSConnectionPool(host='www.freebuf.com,', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001EE139F5BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:43:06   HTTPSConnectionPool(host='account.top', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B4ED0304A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:43:07   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:43:10   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:43:23   HTTPConnectionPool(host='twitter.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EE13A0F320>, 'Connection to twitter.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:43:23   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:43:33   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:43:42   HTTPConnectionPool(host='twitter.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EE13A0FEF0>, 'Connection to twitter.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:44:00   Exceeded 30 redirects.
*********************************************
2019-06-27:16:44:00   HTTPConnectionPool(host='anquan.baidu.com', port=8000): Max retries exceeded with url: /console/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F72677A668>, 'Connection to anquan.baidu.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:44:06   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:44:08   Exceeded 30 redirects.
*********************************************
2019-06-27:16:44:22   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:44:25   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:44:35   HTTPConnectionPool(host='anquan.baidu.com', port=8000): Max retries exceeded with url: /console/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F726F39438>, 'Connection to anquan.baidu.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:44:35   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:44:39   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:44:48   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:03   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:05   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:13   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:18   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:23   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:37   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:38   HTTPConnectionPool(host='m.2cto.com', port=80): Max retries exceeded with url: /kf/qianduan/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B91E9FC940>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:45:39   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:16:45:44   HTTPSConnectionPool(host='vip.2cto.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020565AB0160>, 'Connection to vip.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:45:45   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /os (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42289860>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:45:52   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:45:54   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:46:01   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:46:19   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:46:42   Exceeded 30 redirects.
*********************************************
2019-06-27:16:46:43   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:46:55   Exceeded 30 redirects.
*********************************************
2019-06-27:16:46:58   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:47:02   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:47:17   HTTPConnectionPool(host='pagespeed.report.qq.com', port=80): Max retries exceeded with url: /r.cgi?name= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015C5C0846A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:47:18   HTTPConnectionPool(host='pagespeed.report.qq.com', port=80): Max retries exceeded with url: /r.cgi?name= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015C5C0845F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:47:29   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /wp/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42E03438>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:47:40   HTTPSConnectionPool(host='vip.2cto.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020565BB0898>, 'Connection to vip.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:47:42   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /news/it (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D530DF7208>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:47:42   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91ED52C88>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:47:44   Exceeded 30 redirects.
*********************************************
2019-06-27:16:48:02   HTTPConnectionPool(host='open.t.qq.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000015C5CB1C160>, 'Connection to open.t.qq.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:48:18   HTTPConnectionPool(host='open.t.qq.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000015C5CB1CB38>, 'Connection to open.t.qq.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:48:24   HTTPSConnectionPool(host='music.163.com', port=443): Read timed out.
*********************************************
2019-06-27:16:48:33   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /wp/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42E03B38>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:48:44   HTTPSConnectionPool(host='vip.2cto.com', port=443): Max retries exceeded with url: /wenti/rh/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020565BB05F8>, 'Connection to vip.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:48:45   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: /qq (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91ED524E0>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:48:47   HTTPConnectionPool(host='www.2cto.com', port=80): Max retries exceeded with url: /news/it (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D530DF7FD0>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:49:17   HTTPConnectionPool(host='ad.t.qq.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015C5C01A358>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
*********************************************
2019-06-27:16:49:21   HTTPConnectionPool(host='ad.t.qq.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015C5C01A7B8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
*********************************************
2019-06-27:16:49:30   HTTPConnectionPool(host='pagespeed.report.qq.com', port=80): Max retries exceeded with url: /r.cgi?name= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015C5C01ACC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:49:37   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /cpp/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42DF4AC8>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:49:43   HTTPConnectionPool(host='app.t.qq.com', port=80): Max retries exceeded with url: /?via=WB.TQQ.TOP.APP (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015C5C01A588>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
*********************************************
2019-06-27:16:49:49   HTTPSConnectionPool(host='vip.2cto.com', port=443): Max retries exceeded with url: /wenti/rh/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020565A06DA0>, 'Connection to vip.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:49:50   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: /qq (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91ED52DD8>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:49:52   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /special/oraclebkjc/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D530DF7E48>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:16:49:53   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
***********************************
2019-06-27:16:51:20   HTTPSConnectionPool(host='www.bluenoob.com', port=443): Read timed out.
*********************************************
2019-06-27:16:51:53   HTTPConnectionPool(host='js.touclick.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000019BB508D630>, 'Connection to js.touclick.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:52:12   HTTPConnectionPool(host='js.touclick.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000019BB507C898>, 'Connection to js.touclick.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:53:23   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D531B06278>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:53:25   HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /translate?sl=auto&tl=zh-CN&js=y&prev=_t&hl=zh-CN&ie=UTF-8&u=https://www.sec-wiki.com/weekly/277 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001EE13BAA940>, 'Connection to translate.google.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:53:30   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42211908>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:53:33   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91E8D7160>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:54:26   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /news/qita/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D531B06DA0>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:54:34   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /java/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42E404A8>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:54:35   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: /zz/tuiguang (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91E8D7160>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:55:31   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /news/qita/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D531AFF438>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:55:36   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: /zz/tuiguang (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91E555550>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:55:55   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42F2E0F0>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:56:31   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:56:32   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:56:35   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /special/javasjjg/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D531AFFA90>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:56:41   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: /kf/yidong (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91E555BA8>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:56:58   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /win/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF42F2E630>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:57:50   HTTPConnectionPool(host='cctvenchiridion.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B4ECA87908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:57:53   HTTPConnectionPool(host='cctvenchiridion.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B4ECA87630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:58:16   HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000134AAC48400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
*********************************************
2019-06-27:16:58:31   HTTPConnectionPool(host='music.cc', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F726A45E80>, 'Connection to music.cc timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:58:37   HTTPConnectionPool(host='zcrds.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002264A9481D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:58:40   HTTPConnectionPool(host='zcrds.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002264AB11EB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:16:58:42   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out.
*********************************************
2019-06-27:16:58:45   ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
*********************************************
2019-06-27:16:58:47   HTTPConnectionPool(host='music.cc', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F726479358>, 'Connection to music.cc timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:58:55   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:59:00   HTTPSConnectionPool(host='book.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:16:59:00   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:59:19   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:59:21   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:59:34   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:59:36   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:59:43   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:16:59:46   HTTPConnectionPool(host='cms.cntv.cn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D093AF2630>, 'Connection to cms.cntv.cn timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:59:46   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /special/pythonxxjc/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D531F2E438>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:16:59:50   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: /kf/201111/109891.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91EBDE048>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:00:02   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /webkf/4.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF4313BA58>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:00:06   HTTPConnectionPool(host='cms.cntv.cn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D093AF2F98>, 'Connection to cms.cntv.cn timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:00:40   HTTPConnectionPool(host='tv.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000134AAA290F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:00:44   HTTPConnectionPool(host='tv.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000134AAA29358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:00:49   HTTPConnectionPool(host='music.cctv.com', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:00:50   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /special/pythonxxjc/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D531F2E4A8>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:00:54   HTTPSConnectionPool(host='m.2cto.com', port=443): Max retries exceeded with url: /article/201901/792495.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002B91EBDE710>, 'Connection to m.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:01:05   HTTPConnectionPool(host='book.2cto.com', port=80): Max retries exceeded with url: /www.2cto.com/about/tg.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DF43119160>, 'Connection to book.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:01:10   HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BB4CEA630>, 'Connection to www.google.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:01:27   HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BB4DC7F28>, 'Connection to www.google.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:01:28   HTTPSConnectionPool(host='hacpai.com,', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BB4DD2358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:01:32   HTTPSConnectionPool(host='hacpai.com,', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BB4DD2160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:01:47   HTTPConnectionPool(host='tencentmessage', port=80): Max retries exceeded with url: /?uin=4327814&Site=reg.cn&Menu=yes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002264A6B3358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:01:52   HTTPSConnectionPool(host='www.2cto.com', port=443): Max retries exceeded with url: /special/javayuyanjiaoxue/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D531AA46A0>, 'Connection to www.2cto.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:01:58   HTTPConnectionPool(host='tencentmessage', port=80): Max retries exceeded with url: /?uin=4327814&Site=reg.cn&Menu=yes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002264A6B39B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:02:05   HTTPSConnectionPool(host='static.hacpai.com,', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BB430EA58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:02:06   HTTPSConnectionPool(host='static.hacpai.com,', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BB430E860>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:02:27   HTTPSConnectionPool(host='schema.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D094112EF0>, 'Connection to schema.org timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:02:45   HTTPSConnectionPool(host='schema.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D094252DD8>, 'Connection to schema.org timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:02:49   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:02:52   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:03:02   HTTPSConnectionPool(host='t.me', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DF42235908>, 'Connection to t.me timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:03:18   HTTPSConnectionPool(host='t.me', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DF42248A20>, 'Connection to t.me timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:03:33   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:04:39   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:05:31   HTTPConnectionPool(host='tencentmessage', port=80): Max retries exceeded with url: /?uin=6473776&Site=reg.cn&Menu=yes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002264A904908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:05:37   HTTPConnectionPool(host='tencentmessage', port=80): Max retries exceeded with url: /?uin=6473776&Site=reg.cn&Menu=yes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002264A9042E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:05:43   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:06:03   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:06:32   HTTPConnectionPool(host='tencentmessage', port=80): Max retries exceeded with url: /?uin=4327048&Site=reg.cn&Menu=yes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022649C33550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:07:00   HTTPConnectionPool(host='tencent', port=80): Max retries exceeded with url: //message/?uin=4327048&Site=reg.cn&Menu=yes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022649A57320>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:09:41   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:09:52   HTTPSConnectionPool(host='buy.itunes.apple.com', port=443): Max retries exceeded with url: /WebObjects/MZFinance.woa/wa/redeemLandingPage (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D093BAF470>, 'Connection to buy.itunes.apple.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:09:58   HTTPSConnectionPool(host='www.2cto.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:10:05   HTTPConnectionPool(host='www.xuexila.com', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:10:11   HTTPSConnectionPool(host='buy.itunes.apple.com', port=443): Max retries exceeded with url: /WebObjects/MZFinance.woa/wa/redeemLandingPage (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D094234240>, 'Connection to buy.itunes.apple.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:10:21   Failed to parse: http://    guofeng.yuedu.163.com/source/da07514e72a64d2383c348b2a48bf506_4
    
*********************************************
2019-06-27:17:10:26   Failed to parse: http://    guofeng.yuedu.163.com/source/da07514e72a64d2383c348b2a48bf506_4
    
*********************************************
2019-06-27:17:10:27   Failed to parse: http://    guofeng.yuedu.163.com/source/1c7e78dd0eb348d09e7a62af77d59084_4
    
*********************************************
2019-06-27:17:10:28   Failed to parse: http://    guofeng.yuedu.163.com/source/1c7e78dd0eb348d09e7a62af77d59084_4
    
*********************************************
2019-06-27:17:10:34   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /core/assets/vendor/modernizr/modernizr.min.js?v=3.3.1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA84C2B0>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:10:39   Failed to parse: http://    guofeng.yuedu.163.com/source/fb8691aff636472680240499c5a65778_4
    
*********************************************
2019-06-27:17:10:40   Failed to parse: http://    guofeng.yuedu.163.com/source/fb8691aff636472680240499c5a65778_4
    
*********************************************
2019-06-27:17:10:45   Failed to parse: http://    guofeng.yuedu.163.com/source/642890bed78448a2aa28791d56947632_4
    
*********************************************
2019-06-27:17:10:49   Failed to parse: http://    guofeng.yuedu.163.com/source/642890bed78448a2aa28791d56947632_4
    
*********************************************
2019-06-27:17:10:50   Failed to parse: http://    guofeng.yuedu.163.com/source/f6b60338219141b786f1a9921accb5d9_4
    
*********************************************
2019-06-27:17:10:51   Failed to parse: http://    guofeng.yuedu.163.com/source/f6b60338219141b786f1a9921accb5d9_4
    
*********************************************
2019-06-27:17:10:52   Failed to parse: http://    guofeng.yuedu.163.com/source/f9f4de0739884110a111552a87e6d2d4_4
    
*********************************************
2019-06-27:17:10:54   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /core/assets/vendor/modernizr/modernizr.min.js?v=3.3.1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA847208>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:10:55   Failed to parse: http://    guofeng.yuedu.163.com/source/f9f4de0739884110a111552a87e6d2d4_4
    
*********************************************
2019-06-27:17:11:00   Failed to parse: http://    guofeng.yuedu.163.com/source/7fbb1afaed87415289f6f09900420a52_4
    
*********************************************
2019-06-27:17:11:04   Failed to parse: http://    guofeng.yuedu.163.com/source/7fbb1afaed87415289f6f09900420a52_4
    
*********************************************
2019-06-27:17:11:10   Failed to parse: http://    guofeng.yuedu.163.com/source/3b9f19ddcf864166a2923f778f5b8246_4
    
*********************************************
2019-06-27:17:11:14   Failed to parse: http://    guofeng.yuedu.163.com/source/3b9f19ddcf864166a2923f778f5b8246_4
    
*********************************************
2019-06-27:17:11:14   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /company-profile (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA847E48>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:11:19   HTTPConnectionPool(host='book.tiexue.net', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:11:32   Failed to parse: http://    guofeng.yuedu.163.com/source/0b51ca525f9946aaafdd99eb30d08055_4
    
*********************************************
2019-06-27:17:11:32   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /company-profile (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA8764A8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:11:37   Failed to parse: http://    guofeng.yuedu.163.com/source/0b51ca525f9946aaafdd99eb30d08055_4
    
*********************************************
2019-06-27:17:11:47   HTTPConnectionPool(host='book.tiexue.net', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:11:50   Failed to parse: http://    guofeng.yuedu.163.com/source/137da27250174e3ba52351f63323231b_4
    
*********************************************
2019-06-27:17:11:51   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /shareholder-services/email-alerts (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA876CF8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:11:52   Failed to parse: http://    guofeng.yuedu.163.com/source/137da27250174e3ba52351f63323231b_4
    
*********************************************
2019-06-27:17:11:55   Failed to parse: http://    guofeng.yuedu.163.com/source/68be9a2ffc3746d5aea8a4750dd38ef4_4
    
*********************************************
2019-06-27:17:11:56   Failed to parse: http://    guofeng.yuedu.163.com/source/68be9a2ffc3746d5aea8a4750dd38ef4_4
    
*********************************************
2019-06-27:17:11:57   Failed to parse: http://    guofeng.yuedu.163.com/source/ca46db25083e4582ab5da2ce3660efe5_4
    
*********************************************
2019-06-27:17:12:02   Failed to parse: http://    guofeng.yuedu.163.com/source/ca46db25083e4582ab5da2ce3660efe5_4
    
*********************************************
2019-06-27:17:12:03   Failed to parse: http://    guofeng.yuedu.163.com/source/850c79eaa8e940fdb3ea19d68f507078_4
    
*********************************************
2019-06-27:17:12:07   Failed to parse: http://    guofeng.yuedu.163.com/source/850c79eaa8e940fdb3ea19d68f507078_4
    
*********************************************
2019-06-27:17:12:10   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /shareholder-services/email-alerts (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA84C668>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:12:11   Failed to parse: http://    guofeng.yuedu.163.com/source/233bc53b30b743ba880e20e57b9da590_4
    
*********************************************
2019-06-27:17:12:12   Failed to parse: http://    guofeng.yuedu.163.com/source/233bc53b30b743ba880e20e57b9da590_4
    
*********************************************
2019-06-27:17:12:16   Failed to parse: http://    guofeng.yuedu.163.com/source/2419f5dbbea0484ba8c5ef7be3910f36_4
    
*********************************************
2019-06-27:17:12:18   Failed to parse: http://    guofeng.yuedu.163.com/source/2419f5dbbea0484ba8c5ef7be3910f36_4
    
*********************************************
2019-06-27:17:12:23   Failed to parse: http://    guofeng.yuedu.163.com/source/75ef26c9aa8a47a79bf6c643885ddd9c_4
    
*********************************************
2019-06-27:17:12:25   Failed to parse: http://    guofeng.yuedu.163.com/source/75ef26c9aa8a47a79bf6c643885ddd9c_4
    
*********************************************
2019-06-27:17:12:28   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /stock-information/historical-price-lookup (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA8476D8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:12:30   Failed to parse: http://    guofeng.yuedu.163.com/source/1edb0bce5d4840b8944ccd1e5d795e5d_4
    
*********************************************
2019-06-27:17:12:33   HTTPConnectionPool(host='www.xuexila.com', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:12:35   Failed to parse: http://    guofeng.yuedu.163.com/source/1edb0bce5d4840b8944ccd1e5d795e5d_4
    
*********************************************
2019-06-27:17:12:47   Failed to parse: http://    guofeng.yuedu.163.com/source/1a44089b97c9453bb42820390a00bc76_4
    
*********************************************
2019-06-27:17:12:47   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /stock-information/historical-price-lookup (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA847518>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:12:48   Failed to parse: http://    guofeng.yuedu.163.com/source/1a44089b97c9453bb42820390a00bc76_4
    
*********************************************
2019-06-27:17:12:49   Failed to parse: http://    guofeng.yuedu.163.com/source/2f50a78c6c8f4f8ea1911815ddc49cc4_4
    
*********************************************
2019-06-27:17:12:50   Failed to parse: http://    guofeng.yuedu.163.com/source/2f50a78c6c8f4f8ea1911815ddc49cc4_4
    
*********************************************
2019-06-27:17:12:57   Failed to parse: http://    guofeng.yuedu.163.com/source/b5ad60a40bbf48b086970c4be24c6b30_4
    
*********************************************
2019-06-27:17:12:59   Failed to parse: http://    guofeng.yuedu.163.com/source/b5ad60a40bbf48b086970c4be24c6b30_4
    
*********************************************
2019-06-27:17:13:04   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /static-files/b3317d71-3269-4ab3-8594-7eecada88e6a (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA876748>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:13:11   Failed to parse: http://    guofeng.yuedu.163.com/source/dabd268d79f945009cfdfc30f5b46bf8_4
    
*********************************************
2019-06-27:17:13:16   Failed to parse: http://    guofeng.yuedu.163.com/source/dabd268d79f945009cfdfc30f5b46bf8_4
    
*********************************************
2019-06-27:17:13:21   Failed to parse: http://    guofeng.yuedu.163.com/source/9d929c02d43345168f260e717b6ccb5c_4
    
*********************************************
2019-06-27:17:13:22   Failed to parse: http://    guofeng.yuedu.163.com/source/9d929c02d43345168f260e717b6ccb5c_4
    
*********************************************
2019-06-27:17:13:23   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /static-files/b3317d71-3269-4ab3-8594-7eecada88e6a (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BF9C1E3C8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:13:25   HTTPConnectionPool(host='www.apple.com', port=80): Max retries exceeded with url: /itunes/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D09424FB70>, 'Connection to www.apple.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:13:36   Failed to parse: http://    guofeng.yuedu.163.com/source/dc1262bb0b6a4a16a73fb900925ae38d_4
    
*********************************************
2019-06-27:17:13:41   Failed to parse: http://    guofeng.yuedu.163.com/source/dc1262bb0b6a4a16a73fb900925ae38d_4
    
*********************************************
2019-06-27:17:13:42   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /investor-overview (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BF9C1EC18>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:13:45   Failed to parse: http://    guofeng.yuedu.163.com/source/ts_2e25102817fc45bba0a56ebbeafe6cb8_4
    
*********************************************
2019-06-27:17:13:48   Failed to parse: http://    guofeng.yuedu.163.com/source/ts_2e25102817fc45bba0a56ebbeafe6cb8_4
    
*********************************************
2019-06-27:17:13:50   HTTPConnectionPool(host='safe.webscan.360.cn', port=80): Max retries exceeded with url: /loudong (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000205647F8EB8>, 'Connection to safe.webscan.360.cn timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:14:02   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /investor-overview (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BF9C1E400>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:14:08   Failed to parse: http://    guofeng.yuedu.163.com/source/3073d58d3f8d4aeab50abd63bc3b0ab6_4
    
*********************************************
2019-06-27:17:14:10   HTTPConnectionPool(host='safe.webscan.360.cn', port=80): Max retries exceeded with url: /loudong (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020565E5F438>, 'Connection to safe.webscan.360.cn timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:14:12   Failed to parse: http://    guofeng.yuedu.163.com/source/3073d58d3f8d4aeab50abd63bc3b0ab6_4
    
*********************************************
2019-06-27:17:14:16   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:14:19   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /webcasts-presentations (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BF9C1E4E0>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:14:20   Failed to parse: http://    guofeng.yuedu.163.com/source/c030e38a3eca4000bccf23cdafa77469_4
    
*********************************************
2019-06-27:17:14:25   Failed to parse: http://    guofeng.yuedu.163.com/source/c030e38a3eca4000bccf23cdafa77469_4
    
*********************************************
2019-06-27:17:14:28   Failed to parse: http://    guofeng.yuedu.163.com/source/285fef9f51d743ae8f2f68546b0a60aa_4
    
*********************************************
2019-06-27:17:14:31   Failed to parse: http://    guofeng.yuedu.163.com/source/285fef9f51d743ae8f2f68546b0a60aa_4
    
*********************************************
2019-06-27:17:14:36   Failed to parse: http://    guofeng.yuedu.163.com/source/0670deb760954308bda5671f2fdd0ed5_4
    
*********************************************
2019-06-27:17:14:37   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /webcasts-presentations (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA876128>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:14:38   Failed to parse: http://    guofeng.yuedu.163.com/source/0670deb760954308bda5671f2fdd0ed5_4
    
*********************************************
2019-06-27:17:14:40   Failed to parse: http://    guofeng.yuedu.163.com/source/9c39163e50bc457f877f3ccca1bd82b3_4
    
*********************************************
2019-06-27:17:14:42   Failed to parse: http://    guofeng.yuedu.163.com/source/9c39163e50bc457f877f3ccca1bd82b3_4
    
*********************************************
2019-06-27:17:14:43   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:14:49   Failed to parse: http://    guofeng.yuedu.163.com/source/a2a4841d50e04a31a6185becd23ff999_4
    
*********************************************
2019-06-27:17:14:53   Failed to parse: http://    guofeng.yuedu.163.com/source/a2a4841d50e04a31a6185becd23ff999_4
    
*********************************************
2019-06-27:17:14:55   HTTPConnectionPool(host='book.tiexue.net', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:14:55   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /news-releases (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA84C5F8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:14:58   Failed to parse: http://    guofeng.yuedu.163.com/source/3cc894f9193d4e369c6eaa68ef259ab1_4
    
*********************************************
2019-06-27:17:15:00   Failed to parse: http://    guofeng.yuedu.163.com/source/3cc894f9193d4e369c6eaa68ef259ab1_4
    
*********************************************
2019-06-27:17:15:04   Failed to parse: http://    guofeng.yuedu.163.com/source/7faadbe11bf446ecb568bb498818c791_4
    
*********************************************
2019-06-27:17:15:06   Failed to parse: http://    guofeng.yuedu.163.com/source/7faadbe11bf446ecb568bb498818c791_4
    
*********************************************
2019-06-27:17:15:08   Failed to parse: http://    guofeng.yuedu.163.com/source/ef1adcc4ad8a492cb19193bc95d1974d_4
    
*********************************************
2019-06-27:17:15:11   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /news-releases (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA8477B8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:15:11   Failed to parse: http://    guofeng.yuedu.163.com/source/ef1adcc4ad8a492cb19193bc95d1974d_4
    
*********************************************
2019-06-27:17:15:14   Failed to parse: http://    guofeng.yuedu.163.com/source/af555d7060fd423a8be62834aa62a139_4
    
*********************************************
2019-06-27:17:15:15   Failed to parse: http://    guofeng.yuedu.163.com/source/af555d7060fd423a8be62834aa62a139_4
    
*********************************************
2019-06-27:17:15:19   Failed to parse: http://    guofeng.yuedu.163.com/source/7afb0625ccdb4cf4a969d276cec6e992_4
    
*********************************************
2019-06-27:17:15:20   Failed to parse: http://    guofeng.yuedu.163.com/source/7afb0625ccdb4cf4a969d276cec6e992_4
    
*********************************************
2019-06-27:17:15:21   Failed to parse: http://    guofeng.yuedu.163.com/source/5706b5feba9d424abb8a0dabdfe1b663_4
    
*********************************************
2019-06-27:17:15:26   Failed to parse: http://    guofeng.yuedu.163.com/source/5706b5feba9d424abb8a0dabdfe1b663_4
    
*********************************************
2019-06-27:17:15:28   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /event-calendar (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA847DA0>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:15:29   Failed to parse: http://    guofeng.yuedu.163.com/source/b32f161171944d27936796aba5c53770_4
    
*********************************************
2019-06-27:17:15:31   Failed to parse: http://    guofeng.yuedu.163.com/source/b32f161171944d27936796aba5c53770_4
    
*********************************************
2019-06-27:17:15:42   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:15:42   Failed to parse: http://    guofeng.yuedu.163.com/source/e27b8b2c30dc414ca813f146768767b7_4
    
*********************************************
2019-06-27:17:15:45   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /event-calendar (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BF9C08A20>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:15:47   Failed to parse: http://    guofeng.yuedu.163.com/source/e27b8b2c30dc414ca813f146768767b7_4
    
*********************************************
2019-06-27:17:15:52   Failed to parse: http://    guofeng.yuedu.163.com/source/56e5af4c39494f30b3134c330878fbf2_4
    
*********************************************
2019-06-27:17:15:53   Failed to parse: http://    guofeng.yuedu.163.com/source/56e5af4c39494f30b3134c330878fbf2_4
    
*********************************************
2019-06-27:17:15:57   Failed to parse: http://    guofeng.yuedu.163.com/source/f6308f0d7453457b84d3398899eb0be6_4
    
*********************************************
2019-06-27:17:16:00   Failed to parse: http://    guofeng.yuedu.163.com/source/f6308f0d7453457b84d3398899eb0be6_4
    
*********************************************
2019-06-27:17:16:01   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /shareholder-services/investor-faqs (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA847AC8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:16:03   Failed to parse: http://    guofeng.yuedu.163.com/source/c312198296a64464bbe9281a1259f782_4
    
*********************************************
2019-06-27:17:16:08   Failed to parse: http://    guofeng.yuedu.163.com/source/c312198296a64464bbe9281a1259f782_4
    
*********************************************
2019-06-27:17:16:11   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:16:15   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:16:18   Failed to parse: http://    guofeng.yuedu.163.com/source/0f1a48f73a5c4b6b94a630969105b239_4
    
*********************************************
2019-06-27:17:16:18   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /shareholder-services/investor-faqs (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA8479E8>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:16:20   Failed to parse: http://    guofeng.yuedu.163.com/source/0f1a48f73a5c4b6b94a630969105b239_4
    
*********************************************
2019-06-27:17:16:24   HTTPConnectionPool(host='www.xuexila.com', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:16:25   Failed to parse: http://    guofeng.yuedu.163.com/source/0887419781424583bc2a149fc2555a5b_4
    
*********************************************
2019-06-27:17:16:26   Failed to parse: http://    guofeng.yuedu.163.com/source/0887419781424583bc2a149fc2555a5b_4
    
*********************************************
2019-06-27:17:16:28   Failed to parse: http://    guofeng.yuedu.163.com/source/7d3858eee1f84a1b8990637e5212f6a8_4
    
*********************************************
2019-06-27:17:16:30   Failed to parse: http://    guofeng.yuedu.163.com/source/7d3858eee1f84a1b8990637e5212f6a8_4
    
*********************************************
2019-06-27:17:16:36   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /www.bilibili.com/blackboard/join.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA84C390>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:16:40   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:16:53   HTTPConnectionPool(host='ir.bilibili.com', port=80): Max retries exceeded with url: /www.bilibili.com/blackboard/join.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027BFA876160>, 'Connection to ir.bilibili.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:17:08   HTTPConnectionPool(host='www.xuexila.com', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:17:17   Failed to parse: http://www.shuhai.com (\xca\xe9\xba\xa3\xd0\xa1\xcb\xb5\xcd\xf8)
*********************************************
2019-06-27:17:17:20   Failed to parse: http://www.shuhai.com (\xca\xe9\xba\xa3\xd0\xa1\xcb\xb5\xcd\xf8)
*********************************************
2019-06-27:17:17:32   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:17:50   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:18:27   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:18:35   HTTPConnectionPool(host='www.duwenzhang.com', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:18:47   HTTPConnectionPool(host='www.hao123.com', port=80): Read timed out.
*********************************************
2019-06-27:17:18:51   HTTPConnectionPool(host='www.duwenzhang.com', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:18:53   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:18:56   HTTPSConnectionPool(host='www.hao123.com', port=443): Read timed out.
*********************************************
2019-06-27:17:19:00   No connection adapters were found for '://'
*********************************************
2019-06-27:17:19:02   No connection adapters were found for '://'
*********************************************
2019-06-27:17:19:17   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:19:18   HTTPConnectionPool(host='www.hao123.com', port=80): Read timed out.
*********************************************
2019-06-27:17:19:46   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:20:07   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:20:39   HTTPConnectionPool(host='www.hao123.com', port=80): Read timed out.
*********************************************
2019-06-27:17:21:05   HTTPConnectionPool(host='www.hao123.com', port=80): Read timed out.
*********************************************
2019-06-27:17:21:10   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:21:15   HTTPSConnectionPool(host='www.hao123.com', port=443): Read timed out.
*********************************************
2019-06-27:17:21:29   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:21:30   HTTPConnectionPool(host='mkache.com', port=80): Read timed out.
*********************************************
2019-06-27:17:22:09   HTTPSConnectionPool(host='www.hao123.com', port=443): Read timed out.
***********************************
2019-06-27:17:22:09   list index out of range
*********************************************
2019-06-27:17:22:17   HTTPConnectionPool(host='book.tiexue.net', port=80): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:22:44   list index out of range
*********************************************
2019-06-27:17:24:01   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:24:09   HTTPConnectionPool(host='www.hao123.com', port=80): Read timed out.
*********************************************
2019-06-27:17:24:17   HTTPConnectionPool(host='www.3gsc.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000026FEF8E0630>, 'Connection to www.3gsc.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:24:34   HTTPConnectionPool(host='www.3gsc.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000026FEF8E0390>, 'Connection to www.3gsc.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:24:56   HTTPSConnectionPool(host='book.tiexue.net', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:24:59   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:25:03   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:25:15   HTTPConnectionPool(host='www.one', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022649B18630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:25:16   HTTPConnectionPool(host='www.one', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022649B18550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:27:53   Failed to parse: http://www.jieqi.com (jieqi cms)
*********************************************
2019-06-27:17:27:58   Failed to parse: http://www.jieqi.com (jieqi cms)
*********************************************
2019-06-27:17:28:07   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:28:11   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:28:29   'utf-8' codec can't decode byte 0xb4 in position 20: invalid start byte
*********************************************
2019-06-27:17:28:34   'utf-8' codec can't decode byte 0xb4 in position 20: invalid start byte
*********************************************
2019-06-27:17:28:58   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:28:59   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:28:59   'utf-8' codec can't decode byte 0xb4 in position 17: invalid start byte
*********************************************
2019-06-27:17:29:03   'utf-8' codec can't decode byte 0xb4 in position 17: invalid start byte
*********************************************
2019-06-27:17:29:19   'utf-8' codec can't decode byte 0xb4 in position 17: invalid start byte
*********************************************
2019-06-27:17:29:24   'utf-8' codec can't decode byte 0xb4 in position 17: invalid start byte
*********************************************
2019-06-27:17:30:39   HTTPConnectionPool(host='www.ctwamp.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B92442C4A8>, 'Connection to www.ctwamp.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:30:42   HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015C6EA462B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
*********************************************
2019-06-27:17:30:51   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:30:55   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:30:59   HTTPConnectionPool(host='www.ctwamp.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B92442C160>, 'Connection to www.ctwamp.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:31:01   HTTPConnectionPool(host='www.yunsec.net', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:31:12   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:31:14   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:31:20   HTTPSConnectionPool(host='inmotion-hosting.evyy.net', port=443): Max retries exceeded with url: /c/98608/274454/4222 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D092E4F4A8>, 'Connection to inmotion-hosting.evyy.net timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:31:39   HTTPSConnectionPool(host='inmotion-hosting.evyy.net', port=443): Max retries exceeded with url: /c/98608/274454/4222 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D0938229B0>, 'Connection to inmotion-hosting.evyy.net timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:31:49   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:31:54   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:32:14   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:33:22   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:36:25   HTTPSConnectionPool(host='instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002D49542F7B8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
*********************************************
2019-06-27:17:36:26   HTTPSConnectionPool(host='instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002D49542F748>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
***********************************
2019-06-27:17:36:31   HTTP Error 404: Not Found
***********************************
2019-06-27:17:36:33   HTTP Error 404: Not Found
***********************************
2019-06-27:17:36:33   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:36:35   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:36   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:36   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:36   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:36   HTTP Error 461: 
***********************************
2019-06-27:17:36:37   HTTP Error 461: 
***********************************
2019-06-27:17:36:37   HTTP Error 461: 
***********************************
2019-06-27:17:36:37   HTTP Error 461: 
***********************************
2019-06-27:17:36:37   HTTP Error 461: 
***********************************
2019-06-27:17:36:37   HTTP Error 461: 
***********************************
2019-06-27:17:36:37   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:37   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:38   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:38   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:38   HTTP Error 461: 
***********************************
2019-06-27:17:36:38   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:38   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:38   HTTP Error 461: 
***********************************
2019-06-27:17:36:38   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:36:38   HTTP Error 461: 
***********************************
2019-06-27:17:36:38   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:38   HTTP Error 405: Method Not Allowed
*********************************************
2019-06-27:17:36:38   HTTPSConnectionPool(host='medium.com', port=443): Max retries exceeded with url: /m/global-identity?redirectUrl=https%3A%2F%2Fblog.growthhackers.com%2F (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000172540DFEF0>, 'Connection to medium.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:36:38   HTTP Error 461: 
***********************************
2019-06-27:17:36:38   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:39   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:40   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:40   HTTP Error 461: 
***********************************
2019-06-27:17:36:40   'ascii' codec can't encode characters in position 22-36: ordinal not in range(128)
***********************************
2019-06-27:17:36:41   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:41   HTTP Error 461: 
***********************************
2019-06-27:17:36:41   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:36:41   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:41   HTTP Error 461: 
***********************************
2019-06-27:17:36:41   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:41   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:36:41   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:41   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:41   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:36:41   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:41   HTTP Error 461: 
***********************************
2019-06-27:17:36:42   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:42   HTTP Error 461: 
***********************************
2019-06-27:17:36:42   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:36:42   HTTP Error 405: Method Not Allowed
*********************************************
2019-06-27:17:36:42   HTTPSConnectionPool(host='www.facebook.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FE0CA9F748>, 'Connection to www.facebook.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:36:42   HTTP Error 461: 
***********************************
2019-06-27:17:36:42   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:36:43   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:36:43   'ascii' codec can't encode character '\xe5' in position 22: ordinal not in range(128)
***********************************
2019-06-27:17:36:43   HTTP Error 405: Not Allowed
*********************************************
2019-06-27:17:36:45   HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002268336F748>, 'Connection to www.youtube.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:36:45   timed out
***********************************
2019-06-27:17:36:45   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:45   HTTP Error 461: 
***********************************
2019-06-27:17:36:45   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:45   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:45   HTTP Error 461: 
***********************************
2019-06-27:17:36:46   HTTP Error 405: Not Allowed
*********************************************
2019-06-27:17:36:46   HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001BC8C5CF780>, 'Connection to twitter.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:36:46   HTTP Error 461: 
***********************************
2019-06-27:17:36:46   HTTP Error 404: Not Found
***********************************
2019-06-27:17:36:46   HTTP Error 461: 
***********************************
2019-06-27:17:36:46   HTTP Error 461: 
***********************************
2019-06-27:17:36:46   HTTP Error 461: 
***********************************
2019-06-27:17:36:46   HTTP Error 461: 
***********************************
2019-06-27:17:36:46   HTTP Error 404: Not Found
***********************************
2019-06-27:17:36:46   HTTP Error 461: 
***********************************
2019-06-27:17:36:46   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:47   HTTP Error 404: Not Found
***********************************
2019-06-27:17:36:47   HTTP Error 461: 
***********************************
2019-06-27:17:36:47   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:36:47   HTTP Error 461: 
***********************************
2019-06-27:17:36:47   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:47   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:36:47   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:36:47   HTTP Error 461: 
***********************************
2019-06-27:17:36:47   HTTP Error 461: 
***********************************
2019-06-27:17:36:48   HTTP Error 461: 
***********************************
2019-06-27:17:36:48   HTTP Error 461: 
***********************************
2019-06-27:17:36:48   HTTP Error 461: 
***********************************
2019-06-27:17:36:48   HTTP Error 461: 
***********************************
2019-06-27:17:36:49   HTTP Error 461: 
*********************************************
2019-06-27:17:36:55   HTTPSConnectionPool(host='d31qbv1cthcecs.cloudfront.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002064842F780>, 'Connection to d31qbv1cthcecs.cloudfront.net timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:36:56   HTTP Error 404: Not Found
***********************************
2019-06-27:17:36:56   <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
***********************************
2019-06-27:17:36:58   HTTP Error 500: Internal Server Error
*********************************************
2019-06-27:17:36:59   HTTPSConnectionPool(host='www.facebook.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FE0CA86BE0>, 'Connection to www.facebook.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:37:00   timed out
***********************************
2019-06-27:17:37:01   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:37:01   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:01   HTTP Error 404: Not Found
*********************************************
2019-06-27:17:37:01   HTTPSConnectionPool(host='medium.com', port=443): Max retries exceeded with url: /m/global-identity?redirectUrl=https%3A%2F%2Fblog.growthhackers.com%2F (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001725410C940>, 'Connection to medium.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:37:02   HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001BC8C5B6FD0>, 'Connection to twitter.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:37:02   HTTP Error 501: Not Implemented
*********************************************
2019-06-27:17:37:04   HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000022683356F98>, 'Connection to www.youtube.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:37:05   Failed to parse: https://ssl-static1:http:
***********************************
2019-06-27:17:37:05   'ascii' codec can't encode characters in position 27-28: ordinal not in range(128)
***********************************
2019-06-27:17:37:08   Remote end closed connection without response
***********************************
2019-06-27:17:37:09   <urlopen error Remote end closed connection without response>
***********************************
2019-06-27:17:37:09   HTTP Error 404: Not Found
***********************************
2019-06-27:17:37:10   HTTP Error 405: Not Allowed
*********************************************
2019-06-27:17:37:10   Failed to parse: https://ssl-static1:http:
***********************************
2019-06-27:17:37:10   <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>
***********************************
2019-06-27:17:37:10   HTTP Error 404: Not Found
***********************************
2019-06-27:17:37:11   HTTP Error 404: Not Found
***********************************
2019-06-27:17:37:11   HTTP Error 404: Not Found
***********************************
2019-06-27:17:37:11   HTTP Error 404: Not Found
***********************************
2019-06-27:17:37:12   timed out
***********************************
2019-06-27:17:37:13   HTTP Error 405: Not Allowed
*********************************************
2019-06-27:17:37:14   HTTPSConnectionPool(host='d31qbv1cthcecs.cloudfront.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002064845C2B0>, 'Connection to d31qbv1cthcecs.cloudfront.net timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:37:15   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:37:16   HTTP Error 404: Not Found
***********************************
2019-06-27:17:37:16   HTTP Error 404: Not Found
***********************************
2019-06-27:17:37:17   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:37:18   <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
***********************************
2019-06-27:17:37:20   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:37:21   HTTP Error 501: Method Not Implemented
***********************************
2019-06-27:17:37:25   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:27   timed out
***********************************
2019-06-27:17:37:28   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:37:32   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:37:32   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:37:37   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:37:38   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:37:39   timed out
***********************************
2019-06-27:17:37:42   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:37:44   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:37:48   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:37:50   HTTP Error 403: FORBIDDEN
***********************************
2019-06-27:17:37:51   HTTP Error 493: 
***********************************
2019-06-27:17:37:51   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:37:52   HTTP Error 493: 
***********************************
2019-06-27:17:37:52   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:37:53   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:37:54   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:37:54   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:54   timed out
***********************************
2019-06-27:17:37:55   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:55   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:55   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:55   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:56   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:56   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:56   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:37:57   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:37:59   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:38:00   HTTP Error 404: Not Found
***********************************
2019-06-27:17:38:03   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:38:05   timed out
***********************************
2019-06-27:17:38:05   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:38:06   [WinError 10054] 远程主机强迫关闭了一个现有的连接。
***********************************
2019-06-27:17:38:09   HTTP Error 501: Method Not Implemented
*********************************************
2019-06-27:17:38:10   HTTPConnectionPool(host='schema.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001BC8C616908>, 'Connection to schema.org timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:38:13   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:38:19   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:38:20   timed out
***********************************
2019-06-27:17:38:20   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:38:25   'ascii' codec can't encode characters in position 27-53: ordinal not in range(128)
***********************************
2019-06-27:17:38:27   HTTP Error 405: Method Not Allowed
*********************************************
2019-06-27:17:38:28   HTTPConnectionPool(host='schema.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001BC8C616668>, 'Connection to schema.org timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:38:29   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:38:30   timed out
***********************************
2019-06-27:17:38:34   HTTP Error 501: Method Not Implemented
***********************************
2019-06-27:17:38:37   HTTP Error 501: Method Not Implemented
***********************************
2019-06-27:17:38:37   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:38:45   timed out
*********************************************
2019-06-27:17:38:48   HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/auth?access_type=online&client_id=957843385786-9ilanqmh87stc8im5rfhkhocnc04n3jh.apps.googleusercontent.com&prompt=select_account&redirect_uri=https%3A%2F%2Fa.growthhackers.com%2Fusers%2Fauth%2Fgoogle_oauth2%2Fcallback&response_type=code&scope=email+profile&state=6dd15b7fdaec83147550315a818fe3ef8d7f3702e0a08393 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000183BED2AD68>, 'Connection to accounts.google.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:38:48   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:38:49   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:38:50   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:38:50   HTTP Error 404: Not Found
***********************************
2019-06-27:17:38:51   'ascii' codec can't encode characters in position 29-40: ordinal not in range(128)
***********************************
2019-06-27:17:38:51   HTTP Error 404: Not Found
***********************************
2019-06-27:17:38:51   'ascii' codec can't encode characters in position 19-24: ordinal not in range(128)
***********************************
2019-06-27:17:38:54   HTTP Error 404: Not Found
***********************************
2019-06-27:17:38:57   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:39:00   HTTP Error 501: Not Implemented
*********************************************
2019-06-27:17:39:00   HTTPConnectionPool(host='zhibo.yesky.com', port=80): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:39:00   HTTP Error 404: Not Found
***********************************
2019-06-27:17:39:02   HTTP Error 501: Not Implemented
*********************************************
2019-06-27:17:39:03   HTTPSConnectionPool(host='svg-sprite', port=443): Max retries exceeded with url: /forum.bugcrowd.com/svg-3-8f4d5e8e7fd2dab9db41366b571bb00f04430c01.js (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016067BC6DA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
***********************************
2019-06-27:17:39:06   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:39:07   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:39:07   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:39:10   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:39:10   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:11   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:11   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:11   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:11   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:13   HTTP Error 501: Not Implemented
*********************************************
2019-06-27:17:39:14   HTTPSConnectionPool(host='svg-sprite', port=443): Max retries exceeded with url: /forum.bugcrowd.com/svg-3-8f4d5e8e7fd2dab9db41366b571bb00f04430c01.js (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000160685BBBE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
***********************************
2019-06-27:17:39:15   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:15   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:15   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:15   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:39:16   HTTP Error 404: Not Found
*********************************************
2019-06-27:17:39:20   HTTPConnectionPool(host='zhibo.yesky.com', port=80): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:39:24   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:39:25   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:39:25   'ascii' codec can't encode characters in position 29-34: ordinal not in range(128)
***********************************
2019-06-27:17:39:25   HTTP Error 404: Not Found
***********************************
2019-06-27:17:39:26   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:26   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:26   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:26   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:26   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:27   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:27   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:27   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:33   HTTP Error 404: Not Found
***********************************
2019-06-27:17:39:42   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:39:42   HTTP Error 405: METHOD NOT ALLOWED
***********************************
2019-06-27:17:39:43   HTTP Error 404: Not Found
***********************************
2019-06-27:17:39:49   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:39:51   HTTP Error 404: Not Found
***********************************
2019-06-27:17:39:55   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:56   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:56   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:56   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:56   HTTP Error 412: Precondition Failed
*********************************************
2019-06-27:17:39:56   HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /intent/tweet/?url=https://growthuniversity.teachable.com/courses/593980&text=2019%20GrowthHackers%20Conference%20Virtual%20Pass: (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002D49554B390>, 'Connection to twitter.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:39:56   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:57   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:39:57   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:40:02   HTTP Error 405: Method Not Allowed
***********************************
2019-06-27:17:40:08   HTTP Error 404: Not Found
***********************************
2019-06-27:17:40:08   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:40:08   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:40:09   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:40:09   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:40:09   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:40:10   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:40:11   'ascii' codec can't encode characters in position 27-34: ordinal not in range(128)
***********************************
2019-06-27:17:40:12   HTTP Error 404: Not Found
***********************************
2019-06-27:17:40:12   HTTP Error 404: Not Found
***********************************
2019-06-27:17:40:12   HTTP Error 404: Not Found
***********************************
2019-06-27:17:40:13   HTTP Error 404: Not Found
***********************************
2019-06-27:17:40:13   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:40:13   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:40:14   HTTP Error 403: Forbidden
*********************************************
2019-06-27:17:40:14   HTTPSConnectionPool(host='plus.google.com', port=443): Max retries exceeded with url: /share?url=https://growthuniversity.teachable.com/courses/188213 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002D49554BB38>, 'Connection to plus.google.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:40:18   'ascii' codec can't encode characters in position 26-29: ordinal not in range(128)
***********************************
2019-06-27:17:40:19   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:40:25   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:40:25   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:40:25   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:40:28   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:40:28   HTTP Error 412: Precondition Failed
***********************************
2019-06-27:17:40:28   HTTP Error 412: Precondition Failed
*********************************************
2019-06-27:17:40:28   HTTPConnectionPool(host='fortune.com', port=80): Read timed out.
***********************************
2019-06-27:17:40:28   HTTP Error 412: Precondition Failed
*********************************************
2019-06-27:17:40:50   HTTPSConnectionPool(host='www.facebook.com', port=443): Max retries exceeded with url: /sharer.php?u=https://growthuniversity.teachable.com/courses/142463 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002D49557FA20>, 'Connection to www.facebook.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:40:57   HTTPSConnectionPool(host='highlight-js', port=443): Max retries exceeded with url: /forum.bugcrowd.com/6a88550999021fba7568661984347ac5e0e0b8b7.js (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016068621BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:41:01   HTTPSConnectionPool(host='highlight-js', port=443): Max retries exceeded with url: /forum.bugcrowd.com/6a88550999021fba7568661984347ac5e0e0b8b7.js (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016068621DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:41:07   HTTPConnectionPool(host='tieba.baidu.com', port=80): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:41:08   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:24   <urlopen error Remote end closed connection without response>
***********************************
2019-06-27:17:41:24   HTTP Error 404: Not Found
***********************************
2019-06-27:17:41:24   HTTP Error 404: Not Found
***********************************
2019-06-27:17:41:29   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:30   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:30   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:30   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:30   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:30   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:31   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:31   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:31   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:31   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:31   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:31   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:32   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:33   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:41:33   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:41:34   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:41:34   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:41:34   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:41:34   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:41:35   HTTP Error 307: Temporary Redirect
***********************************
2019-06-27:17:41:36   'ascii' codec can't encode characters in position 21-28: ordinal not in range(128)
***********************************
2019-06-27:17:42:00   <urlopen error Remote end closed connection without response>
***********************************
2019-06-27:17:42:01   IncompleteRead(30872 bytes read)
***********************************
2019-06-27:17:42:03   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:42:07   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:42:09   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:42:24   'ascii' codec can't encode characters in position 60-63: ordinal not in range(128)
***********************************
2019-06-27:17:42:24   'ascii' codec can't encode characters in position 61-64: ordinal not in range(128)
***********************************
2019-06-27:17:42:30   'ascii' codec can't encode character '\xe6' in position 23: ordinal not in range(128)
***********************************
2019-06-27:17:42:41   timed out
***********************************
2019-06-27:17:42:45   浏览器位置粗错1:Message: Timeout loading page after 20000ms

***********************************
2019-06-27:17:42:48   'ascii' codec can't encode character '\xe5' in position 23: ordinal not in range(128)
***********************************
2019-06-27:17:42:49   'ascii' codec can't encode characters in position 23-28: ordinal not in range(128)
***********************************
2019-06-27:17:42:50   'ascii' codec can't encode character '\xe9' in position 62: ordinal not in range(128)
***********************************
2019-06-27:17:42:50   'ascii' codec can't encode character '\xe9' in position 63: ordinal not in range(128)
*********************************************
2019-06-27:17:42:51   HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EEEC8FA860>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
*********************************************
2019-06-27:17:42:55   HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EEEC8FA358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
*********************************************
2019-06-27:17:43:00   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
***********************************
2019-06-27:17:43:01   'ascii' codec can't encode characters in position 29-36: ordinal not in range(128)
***********************************
2019-06-27:17:43:01   timed out
*********************************************
2019-06-27:17:43:05   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
***********************************
2019-06-27:17:43:08   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:43:09   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:43:12   'ascii' codec can't encode characters in position 29-36: ordinal not in range(128)
***********************************
2019-06-27:17:43:13   HTTP Error 404: Not Found
*********************************************
2019-06-27:17:43:15   HTTPConnectionPool(host='fortune.com', port=80): Read timed out.
***********************************
2019-06-27:17:43:18   timed out
***********************************
2019-06-27:17:43:22   HTTP Error 501: Not Implemented
***********************************
2019-06-27:17:43:23   HTTP Error 501: Not Implemented
*********************************************
2019-06-27:17:43:29   HTTPConnectionPool(host='assets.258pcf.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EEEC9076D8>, 'Connection to assets.258pcf.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:43:33   timed out
***********************************
2019-06-27:17:43:41   timed out
***********************************
2019-06-27:17:43:41   timed out
***********************************
2019-06-27:17:43:43   timed out
*********************************************
2019-06-27:17:43:45   HTTPConnectionPool(host='assets.258pcf.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EEEC930320>, 'Connection to assets.258pcf.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:43:48   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:43:49   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:43:49   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:43:49   HTTP Error 405: Not Allowed
***********************************
2019-06-27:17:43:50   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:43:50   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:43:50   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:43:50   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:43:51   HTTP Error 418: 
***********************************
2019-06-27:17:43:51   HTTP Error 418: 
***********************************
2019-06-27:17:43:51   HTTP Error 418: 
***********************************
2019-06-27:17:43:52   HTTP Error 418: 
***********************************
2019-06-27:17:43:52   HTTP Error 418: 
***********************************
2019-06-27:17:43:52   HTTP Error 418: 
***********************************
2019-06-27:17:43:52   HTTP Error 418: 
***********************************
2019-06-27:17:43:53   HTTP Error 418: 
*********************************************
2019-06-27:17:43:53   HTTPConnectionPool(host='nssp.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248B7233160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:43:57   HTTPConnectionPool(host='nssp.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248B72334E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
***********************************
2019-06-27:17:43:59   timed out
***********************************
2019-06-27:17:43:59   'ascii' codec can't encode character '\xe9' in position 23: ordinal not in range(128)
***********************************
2019-06-27:17:44:00   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:44:01   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:44:02   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:44:03   HTTP Error 403: Forbidden
***********************************
2019-06-27:17:44:03   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:44:04   HTTP Error 400: Bad Request
*********************************************
2019-06-27:17:44:10   HTTPConnectionPool(host='info.cc', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EEEC907A20>, 'Connection to info.cc timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:44:21   timed out
***********************************
2019-06-27:17:44:26   <urlopen error Remote end closed connection without response>
*********************************************
2019-06-27:17:44:30   HTTPConnectionPool(host='info.cc', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EEED247518>, 'Connection to info.cc timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:44:34   HTTPSConnectionPool(host='fonts.adobe.com', port=443): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:44:41   timed out
***********************************
2019-06-27:17:44:42   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:44:44   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:44:47   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:44:49   [Errno 11001] getaddrinfo failed
***********************************
2019-06-27:17:45:04   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:05   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:45:06   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:07   HTTP Error 400: Bad Request
***********************************
2019-06-27:17:45:08   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:08   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:09   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:09   HTTP Error 500: Internal Server Error
***********************************
2019-06-27:17:45:09   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:09   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:10   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:12   HTTP Error 405: Method Not Allowed
*********************************************
2019-06-27:17:45:13   HTTPSConnectionPool(host='typekit.com', port=443): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:45:14   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:21   timed out
***********************************
2019-06-27:17:45:22   timed out
***********************************
2019-06-27:17:45:22   HTTP Error 404: Not Found
***********************************
2019-06-27:17:45:36   HTTP Error 404: Not Found
*********************************************
2019-06-27:17:46:08   HTTPSConnectionPool(host='www.linkedin.com', port=443): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:46:10   HTTPConnectionPool(host='fortune.com', port=80): Read timed out.
*********************************************
2019-06-27:17:46:17   HTTPConnectionPool(host='www.jyyuan.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000248B7015B38>, 'Connection to www.jyyuan.com timed out. (connect timeout=15)'))
***********************************
2019-06-27:17:46:22   timed out
***********************************
2019-06-27:17:46:25   HTTP Error 404: Not Found
***********************************
2019-06-27:17:46:30   HTTP Error 400: Invalid HTTP Request
***********************************
2019-06-27:17:46:31   HTTP Error 403: Forbidden
*********************************************
2019-06-27:17:46:33   HTTPConnectionPool(host='www.jyyuan.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000248B7727BA8>, 'Connection to www.jyyuan.com timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:46:38   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:46:41   HTTPConnectionPool(host='fortune.com', port=80): Read timed out.
*********************************************
2019-06-27:17:46:42   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
***********************************
2019-06-27:17:47:02   timed out
***********************************
2019-06-27:17:48:02   timed out
***********************************
2019-06-27:17:48:42   timed out
***********************************
2019-06-27:17:48:49   'ascii' codec can't encode characters in position 39-46: ordinal not in range(128)
*********************************************
2019-06-27:17:49:00   HTTPConnectionPool(host='iot.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB1133E438>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))
*********************************************
2019-06-27:17:49:06   HTTPConnectionPool(host='iot.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BB1133EC88>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))
*********************************************
2019-06-27:17:49:24   HTTPConnectionPool(host='www.c114.net', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:49:40   HTTPConnectionPool(host='www.c114.net', port=80): Read timed out. (read timeout=15)
***********************************
2019-06-27:17:49:43   timed out
*********************************************
2019-06-27:17:50:14   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:16   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:20   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:25   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:29   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:32   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:33   HTTPConnectionPool(host='cul.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020648495128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:50:37   HTTPConnectionPool(host='cul.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206484953C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
*********************************************
2019-06-27:17:50:48   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:55   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:50:58   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:51:01   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:51:19   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:51:21   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:51:23   HTTPConnectionPool(host='mail.sohu.net', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:51:25   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:51:27   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:51:38   HTTPConnectionPool(host='fortune.com', port=80): Read timed out.
*********************************************
2019-06-27:17:51:39   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:51:42   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:51:56   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:52:00   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:52:03   HTTPConnectionPool(host='mail.sohu.net', port=80): Read timed out. (read timeout=15)
*********************************************
2019-06-27:17:52:12   HTTPConnectionPool(host='fortune.com', port=80): Read timed out.
*********************************************
2019-06-27:17:52:40   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:52:42   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:52:45   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:52:50   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:52:53   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:52:58   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:07   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:09   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:09   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:53:09   HTTPConnectionPool(host='www.info', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001BC8D7FFE48>, 'Connection to www.info timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:53:12   ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
*********************************************
2019-06-27:17:53:23   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:27   HTTPConnectionPool(host='www.info', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001BC8D7CA1D0>, 'Connection to www.info timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:53:28   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:30   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:31   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:33   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:34   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:53:47   HTTPConnectionPool(host='tech.cn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001BC8D7CBE10>, 'Connection to tech.cn timed out. (connect timeout=15)'))
*********************************************
2019-06-27:17:53:59   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:54:03   ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
*********************************************
2019-06-27:17:54:07   HTTPConnectionPool(host='tech.cn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001BC8D7CBBA8>, 'Connection to tech.cn timed out. (connect timeout=15)'))
